# Generated by Django 3.1.7 on 2021-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='chara',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AddField(
            model_name='sai',
            name='colour',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AddField(
            model_name='sai',
            name='emotional',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AddField(
            model_name='sai',
            name='friend',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AddField(
            model_name='sai',
            name='quality',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AlterField(
            model_name='sai',
            name='rel',
            field=models.CharField(default='False', max_length=15),
        ),
    ]
