# Generated by Django 3.1.7 on 2021-06-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0004_auto_20210627_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sai',
            name='rel',
            field=models.CharField(max_length=15),
        ),
    ]
